FROM almalinux:10

RUN dnf install -y python3.12 python3.12-devel git-core-2.47.1 curl gcc make && \
    dnf clean all

RUN ln -sf python3.12 /usr/bin/python3

RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python3.12

COPY ../requirements.txt /requirements.txt
RUN pip install --upgrade pip && pip install -r /requirements.txt

WORKDIR /app
COPY ../../ /app

CMD ["bash", "/app/tests/run_all.sh"]
