FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get install -y \
        python3.12 python3.12-venv python3.12-dev \
        git=1:2.47.1-1ubuntu1 \
        curl build-essential \
        && rm -rf /var/lib/apt/lists/*

RUN ln -sf python3.12 /usr/bin/python3

RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python3.12

COPY ../requirements.txt /requirements.txt
RUN pip install --upgrade pip && pip install -r /requirements.txt

WORKDIR /app
COPY ../../ /app

CMD ["bash", "/app/tests/run_all.sh"]
